
#before_install:
#  - sudo apt-get update -qq
#- sudo apt-get install -y  `gxmessage libnotify-bin gmail-notify curl vim-gtk pv cowsay toilet figlet sox libsox-fmt-mp3`
  


before_script:  bash -c ./TRAVIS/before_script.sh 
script:         bash -c ./TRAVIS/test.sh
after_script:   bash -c ./TRAVIS/after_script.sh
branches:
  only:
      - develop
env:
  global:
      - url_travis="http://docs.travis-ci.com/user/build-configuration/"
#  global:
#      - CAMPFIRE_TOKEN=abc123
#      - TIMEOUT=1000
  matrix:
      - USE_NETWORK=true
#GOOD TO KNOW:

#
